In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [185]:
df=pd.read_csv(r"E:\EXcellenC\Projects\Project two\car_data.csv")

In [186]:
df

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071,Almora,2022 Tata Nexon XZ Plus (O) Dark Edition,₹ 9.5 Lakh,"33,000 km","Manual - 6 Gears, Sport Mode",Petrol,Jun 2022,First,Black,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/tata-nex...
10072,Almora,2018 Maruti Suzuki Baleno Delta 1.3,₹ 6.5 Lakh,"65,000 km",Manual - 5 Gears,Diesel,Jun 2018,First,White,"Haridwar Road, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/maruti-s...
10073,Almora,2019 Honda WR-V S MT Petrol,₹ 6.1 Lakh,"29,000 km",Manual - 5 Gears,Petrol,Jun 2019,First,White,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/honda-wr...
10074,Almora,2023 Hyundai Exter SX (O) Connect 1.2 MT,₹ 8 Lakh,"22,000 km",Manual - 5 Gears,Petrol,Jun 2023,Second,Green,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/hyundai-...
10075,Almora,2024 Skoda Kushaq Style 1.5L TSI DSG,₹ 19 Lakh,"6,000 km","Automatic (DCT) - 7 Gears, Manual Override & P...",Petrol,Jun 2024,NaN,Red,"Kaonli, Dehradun",Not Available,Not Available,https://www.carwale.com/used/dehradun/skoda-ku...

In [189]:
df.columns

Index(['City', 'Car Name', 'Price', 'Kilometers Driven', 'Transmission',
       'Fuel Type', 'Manufacturing Year', 'Number of Owners', 'Color',
       'Car Available At', 'Insurance', 'Registration', 'URL'],
      dtype='object')

In [191]:
# Function to extract brand name
def extract_brand(car_name):
    parts = car_name.split()
    if len(parts) >= 2:
        return parts[1]  # Assuming format is: Year Brand Model...
    return None

# Apply the function to the 'car' column
df['brand'] = df['Car Name'].apply(extract_brand)

In [193]:
df.columns

Index(['City', 'Car Name', 'Price', 'Kilometers Driven', 'Transmission',
       'Fuel Type', 'Manufacturing Year', 'Number of Owners', 'Color',
       'Car Available At', 'Insurance', 'Registration', 'URL', 'brand'],
      dtype='object')

In [195]:
df

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL,brand
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...,Tata
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...,MG
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071,Almora,2022 Tata Nexon XZ Plus (O) Dark Edition,₹ 9.5 Lakh,"33,000 km","Manual - 6 Gears, Sport Mode",Petrol,Jun 2022,First,Black,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/tata-nex...,Tata
10072,Almora,2018 Maruti Suzuki Baleno Delta 1.3,₹ 6.5 Lakh,"65,000 km",Manual - 5 Gears,Diesel,Jun 2018,First,White,"Haridwar Road, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/maruti-s...,Maruti
10073,Almora,2019 Honda WR-V S MT Petrol,₹ 6.1 Lakh,"29,000 km",Manual - 5 Gears,Petrol,Jun 2019,First,White,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/honda-wr...,Honda
10074,Almora,2023 Hyundai Exter SX (O) Connect 1.2 MT,₹ 8 Lakh,"22,000 km",Manual - 5 Gears,Petrol,Jun 2023,Second,Green,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/hyundai-...,Hyundai
10075,Almora,2024 Skoda Kushaq Style 1.5L TSI DSG,₹ 19 Lakh,"6,000 km","Automatic (DCT) - 7 Gears, Manual Override & P...",Petrol,Jun 2024,NaN,Red,"Kaonli, Dehradun",Not Available,Not Available,https://www.carwale.com/used/dehradun/skoda-ku...,Skoda

In [197]:
df["brand"].value_counts()

brand
Maruti           2070
Hyundai          1495
Tata              748
Mahindra          670
BMW               656
Mercedes-Benz     618
Honda             612
Toyota            605
Audi              335
Kia               298
Renault           294
Ford              270
Volkswagen        259
MG                210
Skoda             190
Jeep              126
Land               92
Volvo              80
Datsun             72
Nissan             67
MINI               66
Jaguar             60
Porsche            51
Chevrolet          46
Lexus              36
Bentley             7
Maserati            7
Lamborghini         6
Fiat                6
Rolls-Royce         5
Force               5
Hindustan           2
Aston               2
Mitsubishi          2
Ferrari             2
Citroen             1
Ashok               1
Hummer              1
Isuzu               1
BYD                 1
Ssangyong           1
Name: count, dtype: int64

In [199]:
def extract_brand_model(car_name):
    parts = car_name.split()
    if len(parts) >= 3:
        year = parts[0]
        brand = parts[1]
        
        # Check if brand is two words (like "Mercedes-Benz" or "Land Rover")
        if '-' in parts[1] or parts[1].lower() in ['land', 'rolls', 'alfa']: 
            brand = f"{parts[1]} {parts[2]}"
            model = ' '.join(parts[3:])
        else:
            model = ' '.join(parts[2:])
        return pd.Series([brand, model])
    return pd.Series([None, None])

# Apply and create new columns
df[['brand', 'model']] = df['Car Name'].apply(extract_brand_model)

In [201]:
df.columns

Index(['City', 'Car Name', 'Price', 'Kilometers Driven', 'Transmission',
       'Fuel Type', 'Manufacturing Year', 'Number of Owners', 'Color',
       'Car Available At', 'Insurance', 'Registration', 'URL', 'brand',
       'model'],
      dtype='object')

In [203]:
df.head()

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL,brand,model
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz G-Class,G 63 AMG
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...,Tata,Nexon EV XZ Plus
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...,MG,ZS EV Exclusive
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz E-Class,E 220d Exclusive
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz AMG,GLA 35 4MATIC [2021-2023]

In [205]:
df["Price"].isna().sum()

0

In [207]:
df["Kilometers Driven"].isna().sum()

0

In [209]:
df["Transmission"].value_counts()

Transmission
Manual - 5 Gears                                                         4166
Manual - 6 Gears                                                         1303
Automatic (TC) - 8 Gears, Manual Override & Paddle Shift, Sport Mode      253
Automatic - 6 Gears, Manual Override, Sport Mode                          231
Automatic (DCT) - 7 Gears, Manual Override & Paddle Shift, Sport Mode     160
                                                                         ...
Automatic (CVT), Sport Mode                                                 1
Manual - 6 Gears, Paddle Shift, Sport Mode                                  1
Automatic (DCT) - 7 Gears, Sport Mode                                       1
Automatic (AMT) - 4 Gears                                                   1
AMT - 5 Gears, Manual Override, Sport Mode                                  1
Name: count, Length: 128, dtype: int64

In [211]:
# Features to detect
import re
drive_features = {
    'manual_override': 'Manual Override',
    'paddle_shift': 'Paddle Shift',
    'sport_mode': 'Sport Mode'
}

# Extractor function
def extract_transmission_details(row):
    text = str(row)

    # Transmission Type (e.g., 'Automatic (DCT)', 'Manual', etc.)
    trans_match = re.match(r'^([^,-]+?)(?:\s*-\s*|\s*,)', text)
    transmission_type = trans_match.group(1).strip() if trans_match else None

    # Number of Gears
    gears_match = re.search(r'(\d+)\s*Gears', text)
    gears = gears_match.group(1) if gears_match else None

    # Extract features as boolean
    features = {key: feature in text for key, feature in drive_features.items()}

    return pd.Series([
        transmission_type,
        gears,
        features['manual_override'],
        features['paddle_shift'],
        features['sport_mode']
    ])

# Apply to DataFrame
df[['transmission_type', 'gears', 'manual_override', 'paddle_shift', 'sport_mode']] = df['Transmission'].apply(extract_transmission_details)

In [213]:
df

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL,brand,model,transmission_type,gears,manual_override,paddle_shift,sport_mode
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz G-Class,G 63 AMG,Automatic,7,False,True,True
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...,Tata,Nexon EV XZ Plus,Automatic,1,False,False,True
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...,MG,ZS EV Exclusive,Automatic,None,False,False,True
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz E-Class,E 220d Exclusive,Automatic (TC),9,False,True,True
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz AMG,GLA 35 4MATIC [2021-2023],Automatic (DCT),8,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071,Almora,2022 Tata Nexon XZ Plus (O) Dark Edition,₹ 9.5 Lakh,"33,000 km","Manual - 6 Gears, Sport Mode",Petrol,Jun 2022,First,Black,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/tata-nex...,Tata,Nexon XZ Plus (O) Dark Edition,Manual,6,False,False,True
10072,Almora,2018 Maruti Suzuki Baleno Delta 1.3,₹ 6.5 Lakh,"65,000 km",Manual - 5 Gears,Diesel,Jun 2018,First,White,"Haridwar Road, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/maruti-s...,Maruti,Suzuki Baleno Delta 1.3,Manual,5,False,False,False
10073,Almora,2019 Honda WR-V S MT Petrol,₹ 6.1 Lakh,"29,000 km",Manual - 5 Gears,Petrol,Jun 2019,First,White,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/honda-wr...,Honda,WR-V S MT Petrol,Manual,5,False,False,False
10074,Almora,2023 Hyundai Exter SX (O) Connect 1.2 MT,₹ 8 Lakh,"22,000 km",Manual - 5 Gears,Petrol,Jun 2023,Second,Green,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/hyundai-...,Hyundai,Exter SX (O) Connect 1.2 MT,Manual,5,False,False,False
10075,Almora,2024 Skoda Kushaq Style 1.5L TSI DSG,₹ 19 Lakh,"6,000 km","Automatic (DCT) - 7 Gears, Manual Override & P...",Petrol,Jun 2024,NaN,Red,"Kaonli, Dehradun",Not Available,Not Available,https://www.carwale.com/used/dehradun/skoda-ku...,Skoda,Kushaq Style 1.5L TSI DSG,Automatic (DCT),7,True,True,True

In [215]:
df["transmission_type"].value_counts()

transmission_type
Manual                     5696
Automatic                  1924
Automatic (TC)             1013
Automatic (DCT)             402
Automatic (CVT)             288
AMT                         171
Clutchless Manual            64
Automatic (e                 46
Automatic (AMT)              31
Clutchless Manual (IMT)      18
Automatic (EV/Hybrid)        12
Name: count, dtype: int64

In [217]:
df.head(5)

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL,brand,model,transmission_type,gears,manual_override,paddle_shift,sport_mode
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz G-Class,G 63 AMG,Automatic,7,False,True,True
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...,Tata,Nexon EV XZ Plus,Automatic,1,False,False,True
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...,MG,ZS EV Exclusive,Automatic,None,False,False,True
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz E-Class,E 220d Exclusive,Automatic (TC),9,False,True,True
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz AMG,GLA 35 4MATIC [2021-2023],Automatic (DCT),8,False,True,True

In [48]:
df["Fuel Type"].value_counts()

Fuel Type
Petrol                             5347
Diesel                             4063
Electric                            184
CNG                                 163
Petrol + CNG                         83
Hybrid (Electric + Petrol)           79
CNG + CNG                            48
Not Available                        33
Petrol + LPG                         31
Mild Hybrid(Electric + Petrol)       23
Diesel + LPG                          9
Diesel + CNG                          5
Mild Hybrid (Electric + Diesel)       3
Electric Motor                        2
Electric + CNG                        1
Name: count, dtype: int64

In [219]:
df["Number of Owners"].value_counts()

Number of Owners
First            7971
Second           1678
Third             218
4 or More          34
Fourth              6
Not Available       1
Name: count, dtype: int64

In [221]:
df['Number of Owners'] = df['Number of Owners'].replace({
    '4 or More': 'Fourth'
})

In [223]:
df["Number of Owners"].value_counts()

Number of Owners
First            7971
Second           1678
Third             218
Fourth             40
Not Available       1
Name: count, dtype: int64

In [225]:
unique_colors = df['Color'].dropna().unique()

# Print them
print(unique_colors)

['White' 'Black' 'Blue' 'Brown' 'Grey' 'Silver' 'Bronze' 'Red' 'Gold'
 'Orange' 'Maroon' 'Green' 'Purple' 'Beige' 'Alpine White' 'Others'
 'Polar White' 'Volcano Black' 'Smoke Grey' 'Coral White' 'Twilight Blue'
 'Onyx Black' 'Pearl Metallic Arctic White'
 'Pristine White With Black Roof' 'Fiery Black' 'Rising Blue'
 'Ice Cool White' 'Diamond White' 'Metallic Silky Silver' 'Summit White'
 'Typhoon Silver' 'Gray' 'Pearl Arctic White' 'Stone Beige' 'STRIKER BLUE'
 'Titan Grey' 'Pearl Metallic Lucent Orange' 'Pearl white'
 'Superior White' 'Metallic Glistening Grey' 'Silky Silver' 'Other'
 'Switchblade Silver' 'Pearl Snow White' 'Rocky Beige' 'Mist Silver'
 'Platinum White Pearl' 'Milk white' 'Super White ll' 'Porcelain white'
 'Fire Brick Red' 'Storm White' 'Sleek Silver' 'Napoli Black' 'white'
 'Mettalic Azure Grey' 'Moondust Silver' 'P.WHITE' 'Artic White'
 'Daytona Grey' 'Everest White' 'Havana' 'Candy White' 'Crystal White'
 'Gravity Grey' 'Glistening Grey' 'PMA. White' 'Yellow' 'Pure White'
 'Summit white' 'Not Available' 'Sea Grey' 'Solid White' 'Majestic Silver'
 'Withe' 'Pearl White' 'Velocity Blue Metallic' 'Glacier White Pearl'
 'Attitude Black' 'Solid Bright Red' 'Cappuccino Beige' 'Calypso Red'
 'Magnesio Grey' 'Pristine White' 'Super White' 'Prme. Splendid Silver'
 'Nova white' 'Pearl Metallic Auburn Red' 'Arctic White' 'DEEP SEA BLUE'
 'Jupiter Red' 'Royal Gold' 'Glacier white Pearl' 'Minimal Grey'
 'Fiery Orange' 'Aqua teal' 'Grandeur Grey' 'Aurora Black Pearl'
 'Carbon Steel' 'Nexa Blue' 'DARK GREY' 'Red Rage' 'Jet Silver'
 'Magma Grey' 'WHITE' 'Premium Silver' 'Ecru Beige' 'Curcuma Yellow'
 'Golden Brown Metallic' 'Orchid White Pearl'
 'Pearl Metallic Dignity Brown' 'Panther Black' 'TUSCAN RED' 'Phoenix Red'
 'C MICA' 'Patagonia Red' 'Splendid Silver' 'Sterry night' 'Atlas White'
 'Granite Grey' 'Burgundy Red' 'Cayenne Orange' 'Satin White'
 'Bakers Chocolate' 'Bronze Grey' 'Vermilion Red' 'Royal Orchid'
 'Star dust' 'Metallic Woodland Brown' 'Stealth Black' 'Outback Bronze'
 'Pearl Silver' 'Blsky blue' 'Ranger Khaki' 'Mediterranean Blue Metallic'
 'Tropical Mist With Black Roof' 'CHAMPGN_GOLD' 'New Blazing Red'
 'Platinum' 'Glassgow Grey' 'Opal White' 'Dark blue' 'Brilliant Silver'
 'Pearl Blue' 'Prme. Celestial Blue' 'Fiery Red' 'Flash Red'
 'Glaciar White' 'Brilliant Gold' 'Aqua Marine' 'Urban Titanium Metallic'
 'Dynasty Red Metallic' 'Glacier White' 'Sky Grey' 'Nexa Blue (Celestial)'
 'Platinum Silver' 'Super White II' 'Scarlet Sage' 'Wine Red'
 'Titanium Grey' 'Race Blue' 'Sizzling Red Metallic' 'Oyster Grey'
 'Metallic grey' 'Silver Mica' 'Pearl Metallic Midnight Blue'
 'MET GRANITE GREY' 'Bluish Black' 'Radiant Red Metallic' 'Calgary White'
 'Sizzling Red' 'Taffeta White' 'Mint White' 'Prlwhite' 'Waite coler'
 'Solid Fire Red' 'Pearlescent White' 'New Torque Blue'
 'Metallic Magma Grey' 'Blazing Red' 'Sandrif Grey' 'Pearl Supreme White'
 'Bright Silver' 'Silky Silver Metallic' 'Pepper Grey' 'Breeze Blue'
 'Symphony Silver' 'Blushing red' 'Phantom Black' 'Glaze Red' 'Squeeze'
 'Maharaja Red' 'Palladium Silver' 'Platinum White Pearl with Black Roof'
 'Skyscraper metallic' 'GRAY' 'JAVA BROWN' 'Caribbean Blue Metallic'
 'Biege' 'Pristine Blue' 'Oryx White' 'Metallic Clear Beige' 'Silky gold'
 'Nexa blue' 'Moonlight Silver' 'black' 'Desert Myst' 'Cavern Grey'
 'Brick Red' 'PORCLN_WHITE' 'Zingers blue' 'Fire red' 'Stone Black'
 'Silky Gold Mica Metallic' 'Pure white' 'Pristine White Dual Tone'
 'Superwhite' 'NEW PEARL WHITE' 'PLATINUM_SLV' 'Cafe White' 'MALBSL_GLYBK'
 'Pearl Sangria Red' 'Colorado Red' 'Arctic Silver' 'Metal Mustard'
 'Gravity Gray' 'Satin Copper, Infinity Blue' 'Foliage Green'
 'Sand Drift Grey' 'Royale Blue' 'IRISH CREAM' 'Clear White'
 'Enticing Silver' 'TEABLU_PREWT' 'SEAGREY' 'Dignity Brown' 'Marina Blue'
 'Pearl Blue Blaze' 'Midnight Black' 'Mojave Silver' 'Orcus White'
 'Sportin Red' 'S WHITE' 'AVEWHT BKONX' 'FOREST GREEN' 'Rouge Red'
 'PEARL BLUE' 'SWITCH B SILVER' 'ECO GREEN' 'Pearl Silver Metallic'
 'Ruby Red' 'silver' 'Sunlight Copper' 'SILKY SILVER' 'BLAZING RED'
 'V RED' 'Opulent Red' 'Crystal Silver' 'Ibis White' 'D WHITE'
 'INGOT SILV' 'Other colors' 'Fuji White' 'Cosmos Black Metallic'
 'Aurora Silver' 'M Portimao Blue Metallic' 'Rosso Brunello'
 'Iridium Silver' 'Firmament Blue Metallic' 'Sunset Red' 'Garnet Red'
 'Sparkling Silver' 'Oberon Black' 'Starry Black' 'Mountain Grey'
 'Carrara White' 'P M A WHITE' 'CARARRA WHITE' 'Avant Garde Bronze'
 'MET PREM SILVER' 'Gallant Red' 'Cirrus White' 'Cavansite Blue'
 'Glaze Red with Starry Black' 'Arctic Grey Brilliant Effect Metallic'
 'U TITANIUM' 'Cavansite Blue Metallic' 'green' 'METALLIC PREMIUM SIL'
 'Brilliant Black' 'Sardinia Red' 'MFRED' 'Red Passion' 'F RED'
 'Silver Mica Metallic' 'Clear Beige' 'P WHITE' 'Magic Black'
 'PEARL WHITE' 'PUREWHIE' 'BLUE' 'Pacific Blue' 'S SILVER' 'A WHITE'
 'Artic Silver' 'Oxford White' 'Aqua Teal' 'Starry black' 'Racing Red'
 'Champagne Gold' 'Blade Silver' 'PLANET GREY' 'New Granite Grey'
 'Dynamo Red' 'Reflex Silver' 'STAR DUST' 'Blue Metallic' 'L.PURPLE'
 'Dazzling Silver' 'Metallic Granite Grey' 'Abyss Black' 'PORCLN WHITE'
 'Grey Mica Metallic' 'Flamenco Red' 'Electric Red' 'Quartz Black'
 'Classic Grey' 'Silver Mica Metalic' 'DEEP FOREST' 'Avenue White'
 'FOLIAG green' 'GLISTENINGGREY' 'PRME.DIG.BROWN' 'Insta Blue'
 'Intense Red' 'PMAW' 'Tafeta White' 'Chill Metallic' 'Typhoon silver'
 'Dazzling silver' 'Planet Grey' 'SUPERIOR WHITE'
 'Sparkling Black Cystal Shine' 'PLT' 'Wite' 'Star Dust'
 'Ocean Blue Metallic' 'Mythos Black' 'Mythos Black Metallic'
 'Titanium Beige' 'Bold Beige Metallic' 'Wild Cherry Red' 'Tornado Red'
 'Metal Mustard with Black Roof' 'Obsidian Black' 'Matte Graphite'
 'Platinum grey DT zo' 'H. RED' 'Arcade Grey' 'Etna Orange' 'Radiant Red'
 'Carbon Bronze Pearl' 'Starry Night' 'Magnet green' 'ATL_BLACK_DK'
 'Torque Blue' 'Oxford Blue' 'Real Earth Metallic' 'Wine Red Metallic'
 'Metallic Moonlight Silver' 'Robust Emerald Pearl' 'Alabaster Silver'
 'Passion Red Metallic' 'Malabar Silver' 'ALP Blue' 'Flamboyant Red'
 'R PASSION' 'MET. P. SILVER' 'M G GREY' 'CHAMPAGNE' 'StarDust'
 'Paprika Red' 'TRO-MIST-ADV' 'Urban Titanium' 'FIERY RED' 'RED'
 'Copper Dazzle' 'Canyon Ridge' 'DRIZZLE SILVER' 'Stardust'
 'Pearl Galaxy Black' 'Crystal Black Pearl' 'METALLIC BAKERS CHOC'
 'Carnelian Red Pearl' 'Absolute Black' 'Super Red' 'Urben titanium'
 'Switch Blade Silver' 'Black Sapphire Metallic' 'Zanskar Blue'
 'Opulent Purple' 'Silver Metallic' 'Deep Grey']

In [227]:
car_insurance = df['Insurance'].dropna().unique()

# Print them
print(car_insurance)

['Comprehensive' 'Not Available' 'Zero Depreciation' 'Third Party'
 'Expired' 'No Insurance']

In [229]:
df["Insurance"].value_counts()

Insurance
Comprehensive        3737
Not Available        2522
Expired              2413
Third Party           854
Zero Depreciation     531
No Insurance           19
Name: count, dtype: int64

In [231]:
df.columns

Index(['City', 'Car Name', 'Price', 'Kilometers Driven', 'Transmission',
       'Fuel Type', 'Manufacturing Year', 'Number of Owners', 'Color',
       'Car Available At', 'Insurance', 'Registration', 'URL', 'brand',
       'model', 'transmission_type', 'gears', 'manual_override',
       'paddle_shift', 'sport_mode'],
      dtype='object')

In [234]:
df

,City,Car Name,Price,Kilometers Driven,Transmission,Fuel Type,Manufacturing Year,Number of Owners,Color,Car Available At,Insurance,Registration,URL,brand,model,transmission_type,gears,manual_override,paddle_shift,sport_mode
0,Mumbai,2013 Mercedes-Benz G-Class G 63 AMG,₹ 88 Lakh,"85,000 km","Automatic - 7 Gears, Paddle Shift, Sport Mode",Petrol,Jun 2013,Third,White,"Kurla East, Mumbai",Comprehensive,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz G-Class,G 63 AMG,Automatic,7,False,True,True
1,Mumbai,2021 Tata Nexon EV XZ Plus,₹ 9.25 Lakh,"18,500 km","Automatic - 1 Gears, Sport Mode",Electric,Apr 2021,First,White,"Andheri (E), Mumbai",Comprehensive,Apr 2021,https://www.carwale.com/used/mumbai/tata-nexon...,Tata,Nexon EV XZ Plus,Automatic,1,False,False,True
2,Mumbai,2023 MG ZS EV Exclusive,₹ 18.45 Lakh,"8,900 km","Automatic - Not Applicable Gears, Sport Mode",Electric,Feb 2023,First,Black,"Goregaon (W), Mumbai",Not Available,Feb 2023,https://www.carwale.com/used/mumbai/mg-zs-ev/b...,MG,ZS EV Exclusive,Automatic,None,False,False,True
3,Mumbai,2020 Mercedes-Benz E-Class E 220d Exclusive,₹ 41.75 Lakh,"28,000 km","Automatic (TC) - 9 Gears, Paddle Shift, Sport ...",Diesel,Jun 2020,First,Blue,"Andheri (W), Mumbai",Zero Depreciation,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz E-Class,E 220d Exclusive,Automatic (TC),9,False,True,True
4,Mumbai,2022 Mercedes-Benz AMG GLA 35 4MATIC [2021-2023],₹ 49.99 Lakh,"7,400 km","Automatic (DCT) - 8 Gears, Paddle Shift, Sport...",Petrol,Jun 2022,First,Black,"Borivali (W), Mumbai",Third Party,Not Available,https://www.carwale.com/used/mumbai/mercedes-b...,Mercedes-Benz AMG,GLA 35 4MATIC [2021-2023],Automatic (DCT),8,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071,Almora,2022 Tata Nexon XZ Plus (O) Dark Edition,₹ 9.5 Lakh,"33,000 km","Manual - 6 Gears, Sport Mode",Petrol,Jun 2022,First,Black,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/tata-nex...,Tata,Nexon XZ Plus (O) Dark Edition,Manual,6,False,False,True
10072,Almora,2018 Maruti Suzuki Baleno Delta 1.3,₹ 6.5 Lakh,"65,000 km",Manual - 5 Gears,Diesel,Jun 2018,First,White,"Haridwar Road, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/maruti-s...,Maruti,Suzuki Baleno Delta 1.3,Manual,5,False,False,False
10073,Almora,2019 Honda WR-V S MT Petrol,₹ 6.1 Lakh,"29,000 km",Manual - 5 Gears,Petrol,Jun 2019,First,White,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/honda-wr...,Honda,WR-V S MT Petrol,Manual,5,False,False,False
10074,Almora,2023 Hyundai Exter SX (O) Connect 1.2 MT,₹ 8 Lakh,"22,000 km",Manual - 5 Gears,Petrol,Jun 2023,Second,Green,"Kaonli, Dehradun",Comprehensive,Not Available,https://www.carwale.com/used/dehradun/hyundai-...,Hyundai,Exter SX (O) Connect 1.2 MT,Manual,5,False,False,False
10075,Almora,2024 Skoda Kushaq Style 1.5L TSI DSG,₹ 19 Lakh,"6,000 km","Automatic (DCT) - 7 Gears, Manual Override & P...",Petrol,Jun 2024,NaN,Red,"Kaonli, Dehradun",Not Available,Not Available,https://www.carwale.com/used/dehradun/skoda-ku...,Skoda,Kushaq Style 1.5L TSI DSG,Automatic (DCT),7,True,True,True

In [242]:
df.columns

Index(['City', 'Car Name', 'Price', 'Kilometers Driven', 'Transmission',
       'Fuel Type', 'Manufacturing Year', 'Number of Owners', 'Color',
       'Car Available At', 'Insurance', 'Registration', 'URL', 'brand',
       'model', 'transmission_type', 'gears', 'manual_override',
       'paddle_shift', 'sport_mode'],
      dtype='object')

In [244]:
df.to_csv("CAR_DATANEW.csv", index=False)

In [246]:
df.to_csv(r"E:\EXcellenC\Projects\Project two\CAR_DATANEW.csv", index=False)